export const subject4 = [
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508120,
    nombreMateria: "INTRODUCCIÓN A LA INGENIERÍA DE SISTEMAS",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 1,
    nombreBancoElectivas: " ",
    nivel: 1,
    creditos: 1,
    requisitos: [],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2536101,
    nombreMateria: "DESCUBRIENDO LA FÍSICA",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 2,
    nombreBancoElectivas: " ",
    nivel: 1,
    creditos: 3,
    requisitos: [],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2555121,
    nombreMateria: "GEOMETRÍA VECTORIAL Y ANALÍTICA",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 3,
    nombreBancoElectivas: " ",
    nivel: 1,
    creditos: 3,
    requisitos: [],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2555131,
    nombreMateria: "CÁLCULO DIFERENCIAL",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 4,
    nombreBancoElectivas: " ",
    nivel: 1,
    creditos: 3,
    requisitos: [
      {
        materia: 2555101,
        nombreMateria: "ÁLGEBRA Y TRIGONOMETRÍA",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 5,
        nombreBancoElectivas: "  ",
        tipoRequisito: "CORREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2555101,
    nombreMateria: "ÁLGEBRA Y TRIGONOMETRÍA",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 5,
    nombreBancoElectivas: " ",
    nivel: 1,
    creditos: 3,
    requisitos: [],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2537101,
    nombreMateria: "VIVAMOS LA UNIVERSIDAD",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 6,
    nombreBancoElectivas: " ",
    nivel: 1,
    creditos: 1,
    requisitos: [],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2538101,
    nombreMateria: "INGLÉS I",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 7,
    nombreBancoElectivas: " ",
    nivel: 1,
    creditos: 1,
    requisitos: [],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508207,
    nombreMateria: "MATEMÁTICAS DISCRETAS I",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 8,
    nombreBancoElectivas: " ",
    nivel: 2,
    creditos: 3,
    requisitos: [
      {
        materia: 2508120,
        nombreMateria: "INTRODUCCIÓN A LA INGENIERÍA DE SISTEMAS",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 1,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508208,
    nombreMateria: "LÓGICA Y REPRESENTACIÓN I",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 9,
    nombreBancoElectivas: " ",
    nivel: 2,
    creditos: 3,
    requisitos: [
      {
        materia: 2508207,
        nombreMateria: "MATEMÁTICAS DISCRETAS I",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 8,
        nombreBancoElectivas: "  ",
        tipoRequisito: "CORREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2536201,
    nombreMateria: "FÍSICA MECÁNICA",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 10,
    nombreBancoElectivas: " ",
    nivel: 2,
    creditos: 3,
    requisitos: [
      {
        materia: 2536101,
        nombreMateria: "DESCUBRIENDO LA FÍSICA",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 2,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 2555121,
        nombreMateria: "GEOMETRÍA VECTORIAL Y ANALÍTICA",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 3,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 2555131,
        nombreMateria: "CÁLCULO DIFERENCIAL",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 4,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2555221,
    nombreMateria: "ÁLGEBRA LINEAL",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 11,
    nombreBancoElectivas: " ",
    nivel: 2,
    creditos: 3,
    requisitos: [
      {
        materia: 2555121,
        nombreMateria: "GEOMETRÍA VECTORIAL Y ANALÍTICA",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 3,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 2555101,
        nombreMateria: "ÁLGEBRA Y TRIGONOMETRÍA",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 5,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2555231,
    nombreMateria: "CÁLCULO INTEGRAL",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 12,
    nombreBancoElectivas: " ",
    nivel: 2,
    creditos: 3,
    requisitos: [
      {
        materia: 2555131,
        nombreMateria: "CÁLCULO DIFERENCIAL",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 4,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 2555101,
        nombreMateria: "ÁLGEBRA Y TRIGONOMETRÍA",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 5,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2539101,
    nombreMateria: "LECTOESCRITURA",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 13,
    nombreBancoElectivas: " ",
    nivel: 2,
    creditos: 3,
    requisitos: [
      {
        materia: 2537101,
        nombreMateria: "VIVAMOS LA UNIVERSIDAD",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 6,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2538201,
    nombreMateria: "INGLÉS II",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 14,
    nombreBancoElectivas: " ",
    nivel: 2,
    creditos: 1,
    requisitos: [
      {
        materia: 2538101,
        nombreMateria: "INGLÉS I",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 7,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508303,
    nombreMateria: "MATEMÁTICAS DISCRETAS II",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 15,
    nombreBancoElectivas: " ",
    nivel: 3,
    creditos: 3,
    requisitos: [
      {
        materia: 2508207,
        nombreMateria: "MATEMÁTICAS DISCRETAS I",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 8,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508306,
    nombreMateria: "LÓGICA Y REPRESENTACIÓN II",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 16,
    nombreBancoElectivas: " ",
    nivel: 3,
    creditos: 3,
    requisitos: [
      {
        materia: 2508303,
        nombreMateria: "MATEMÁTICAS DISCRETAS II",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 15,
        nombreBancoElectivas: "  ",
        tipoRequisito: "CORREQ",
      },
      {
        materia: 2508208,
        nombreMateria: "LÓGICA Y REPRESENTACIÓN I",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 9,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508307,
    nombreMateria: "TÉCNICAS DE PROGRAMACIÓN Y LABORATORIO",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 17,
    nombreBancoElectivas: " ",
    nivel: 3,
    creditos: 4,
    requisitos: [
      {
        materia: 2508306,
        nombreMateria: "LÓGICA Y REPRESENTACIÓN II",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 16,
        nombreBancoElectivas: "  ",
        tipoRequisito: "CORREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508308,
    nombreMateria: "TEORÍA DE LA PROBABILIDAD Y COLAS",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 18,
    nombreBancoElectivas: " ",
    nivel: 3,
    creditos: 4,
    requisitos: [
      {
        materia: 2555231,
        nombreMateria: "CÁLCULO INTEGRAL",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 12,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2538301,
    nombreMateria: "INGLÉS III",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 19,
    nombreBancoElectivas: " ",
    nivel: 3,
    creditos: 1,
    requisitos: [
      {
        materia: 2538201,
        nombreMateria: "INGLÉS II",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 14,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508402,
    nombreMateria: "LÓGICA Y REPRESENTACIÓN III",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 20,
    nombreBancoElectivas: " ",
    nivel: 4,
    creditos: 4,
    requisitos: [
      {
        materia: 2508306,
        nombreMateria: "LÓGICA Y REPRESENTACIÓN II",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 16,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508403,
    nombreMateria: "ANÁLISIS Y DISEÑO DE SISTEMAS I",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 21,
    nombreBancoElectivas: " ",
    nivel: 4,
    creditos: 4,
    requisitos: [
      {
        materia: 2508307,
        nombreMateria: "TÉCNICAS DE PROGRAMACIÓN Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 17,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508408,
    nombreMateria: "MÉTODOS ESTADISTICOS",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 22,
    nombreBancoElectivas: " ",
    nivel: 4,
    creditos: 3,
    requisitos: [
      {
        materia: 2508308,
        nombreMateria: "TEORÍA DE LA PROBABILIDAD Y COLAS",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 18,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508407,
    nombreMateria: "ECUACIONES DIFERENCIALES Y MÉTODOS NUMÉRICOS",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 23,
    nombreBancoElectivas: " ",
    nivel: 4,
    creditos: 3,
    requisitos: [
      {
        materia: 2555221,
        nombreMateria: "ÁLGEBRA LINEAL",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 11,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 2555231,
        nombreMateria: "CÁLCULO INTEGRAL",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 12,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 2508307,
        nombreMateria: "TÉCNICAS DE PROGRAMACIÓN Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 17,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2538401,
    nombreMateria: "INGLÉS IV",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 24,
    nombreBancoElectivas: " ",
    nivel: 4,
    creditos: 1,
    requisitos: [
      {
        materia: 2538301,
        nombreMateria: "INGLÉS III",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 19,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508508,
    nombreMateria: "TEORÍA DE LENGUAJES Y LABORATORIO",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 25,
    nombreBancoElectivas: " ",
    nivel: 5,
    creditos: 4,
    requisitos: [
      {
        materia: 2508402,
        nombreMateria: "LÓGICA Y REPRESENTACIÓN III",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 20,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508506,
    nombreMateria: "ANÁLISIS Y DISEÑO DE SISTEMAS II",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 26,
    nombreBancoElectivas: " ",
    nivel: 5,
    creditos: 3,
    requisitos: [
      {
        materia: 2508403,
        nombreMateria: "ANÁLISIS Y DISEÑO DE SISTEMAS I",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 21,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508507,
    nombreMateria: "ESTRUCTURA DE DATOS Y LABORATORIO",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 27,
    nombreBancoElectivas: " ",
    nivel: 5,
    creditos: 4,
    requisitos: [
      {
        materia: 2508402,
        nombreMateria: "LÓGICA Y REPRESENTACIÓN III",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 20,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508509,
    nombreMateria: "MODELOS Y SIMULACIÓN DE SISTEMAS I",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 28,
    nombreBancoElectivas: " ",
    nivel: 5,
    creditos: 3,
    requisitos: [
      {
        materia: 2508408,
        nombreMateria: "MÉTODOS ESTADISTICOS",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 22,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 2508407,
        nombreMateria: "ECUACIONES DIFERENCIALES Y MÉTODOS NUMÉRICOS",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 23,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2517362,
    nombreMateria: "FORMACIÓN CIUDADANA Y CONSTITUCIONAL",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 29,
    nombreBancoElectivas: " ",
    nivel: 5,
    creditos: 1,
    requisitos: [],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2538501,
    nombreMateria: "INGLÉS V",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 30,
    nombreBancoElectivas: " ",
    nivel: 5,
    creditos: 1,
    requisitos: [
      {
        materia: 2538401,
        nombreMateria: "INGLÉS IV",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 24,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508608,
    nombreMateria: "ARQUITECTURA DE SOFTWARE",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 31,
    nombreBancoElectivas: " ",
    nivel: 6,
    creditos: 3,
    requisitos: [
      {
        materia: 2508609,
        nombreMateria: "BASES DE DATOS Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 32,
        nombreBancoElectivas: "  ",
        tipoRequisito: "CORREQ",
      },
      {
        materia: 2508506,
        nombreMateria: "ANÁLISIS Y DISEÑO DE SISTEMAS II",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 26,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508609,
    nombreMateria: "BASES DE DATOS Y LABORATORIO",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 32,
    nombreBancoElectivas: " ",
    nivel: 6,
    creditos: 4,
    requisitos: [
      {
        materia: 2508507,
        nombreMateria: "ESTRUCTURA DE DATOS Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 27,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508611,
    nombreMateria: "MODELOS Y SIMULACIÓN DE SISTEMAS II",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 33,
    nombreBancoElectivas: " ",
    nivel: 6,
    creditos: 4,
    requisitos: [
      {
        materia: 2508509,
        nombreMateria: "MODELOS Y SIMULACIÓN DE SISTEMAS I",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 28,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508610,
    nombreMateria: "COMUNICACIONES Y LABORATORIO",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 34,
    nombreBancoElectivas: " ",
    nivel: 6,
    creditos: 4,
    requisitos: [
      {
        materia: 2508402,
        nombreMateria: "LÓGICA Y REPRESENTACIÓN III",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 20,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2538601,
    nombreMateria: "INGLÉS VI",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 35,
    nombreBancoElectivas: " ",
    nivel: 6,
    creditos: 1,
    requisitos: [
      {
        materia: 2538501,
        nombreMateria: "INGLÉS V",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 30,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508700,
    nombreMateria: "PROYECTO INTEGRADOR I",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 36,
    nombreBancoElectivas: " ",
    nivel: 7,
    creditos: 2,
    requisitos: [],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508701,
    nombreMateria: "FUNDAMENTOS DE INVESTIGACIÓN",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 37,
    nombreBancoElectivas: " ",
    nivel: 7,
    creditos: 3,
    requisitos: [
      {
        materia: 2508506,
        nombreMateria: "ANÁLISIS Y DISEÑO DE SISTEMAS II",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 26,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508702,
    nombreMateria: "FUNDAMENTOS DE SISTEMAS DE INFORMACIÓN",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 38,
    nombreBancoElectivas: " ",
    nivel: 7,
    creditos: 3,
    requisitos: [
      {
        materia: 2508403,
        nombreMateria: "ANÁLISIS Y DISEÑO DE SISTEMAS I",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 21,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508703,
    nombreMateria: "CALIDAD DE SOFTWARE",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 39,
    nombreBancoElectivas: " ",
    nivel: 7,
    creditos: 3,
    requisitos: [
      {
        materia: 2508608,
        nombreMateria: "ARQUITECTURA DE SOFTWARE",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 31,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508716,
    nombreMateria: "ARQUITECTURA DE COMPUTADORES Y LABORATORIO",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 40,
    nombreBancoElectivas: " ",
    nivel: 7,
    creditos: 4,
    requisitos: [
      {
        materia: 2508303,
        nombreMateria: "MATEMÁTICAS DISCRETAS II",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 15,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508836,
    nombreMateria: "ÉTICA PROFESIONAL",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 41,
    nombreBancoElectivas: " ",
    nivel: 8,
    creditos: 1,
    requisitos: [
      {
        materia: 2508701,
        nombreMateria: "FUNDAMENTOS DE INVESTIGACIÓN",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 37,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508840,
    nombreMateria: "COMUNICACIONES II",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 42,
    nombreBancoElectivas: " ",
    nivel: 8,
    creditos: 3,
    requisitos: [
      {
        materia: 2508610,
        nombreMateria: "COMUNICACIONES Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 34,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508841,
    nombreMateria: "GESTIÓN DE PROYECTOS DE SISTEMAS DE INFORMACIÓN",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 43,
    nombreBancoElectivas: " ",
    nivel: 8,
    creditos: 3,
    requisitos: [
      {
        materia: 2508702,
        nombreMateria: "FUNDAMENTOS DE SISTEMAS DE INFORMACIÓN",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 38,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508842,
    nombreMateria: "SISTEMAS OPERATIVOS Y LABORATORIO",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 44,
    nombreBancoElectivas: " ",
    nivel: 8,
    creditos: 4,
    requisitos: [
      {
        materia: 2508507,
        nombreMateria: "ESTRUCTURA DE DATOS Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 27,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 2508716,
        nombreMateria: "ARQUITECTURA DE COMPUTADORES Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 40,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508902,
    nombreMateria: "PROYECTO INTEGRADOR II - ÁREA ELECTIVA",
    tipoMateria: "OBLIGATORIA",
    consecutivoMateria: 45,
    nombreBancoElectivas: " ",
    nivel: 9,
    creditos: 2,
    requisitos: [
      {
        materia: 2508700,
        nombreMateria: "PROYECTO INTEGRADOR I",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 36,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2536302,
    nombreMateria: "FÍSICA DE ONDAS",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9001,
    nombreBancoElectivas: "BANCO ALTERNATIVO DE SÍSICA",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2536201,
        nombreMateria: "FÍSICA MECÁNICA",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 10,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 2555231,
        nombreMateria: "CÁLCULO INTEGRAL",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 12,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2536311,
    nombreMateria: "FÍSICA DE CAMPOS",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9001,
    nombreBancoElectivas: "BANCO ALTERNATIVO DE SÍSICA",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2536201,
        nombreMateria: "FÍSICA MECÁNICA",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 10,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 2555231,
        nombreMateria: "CÁLCULO INTEGRAL",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 12,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2536321,
    nombreMateria: "FISICA TERMICA",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9001,
    nombreBancoElectivas: "BANCO ALTERNATIVO DE SÍSICA",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2536201,
        nombreMateria: "FÍSICA MECÁNICA",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 10,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 2555231,
        nombreMateria: "CÁLCULO INTEGRAL",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 12,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2536500,
    nombreMateria: "LABORATORIO INTEGRADO DE FISICA",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9002,
    nombreBancoElectivas: "BANCO ALTERNATIVO LABORATORI INTEGRADO DE FÍSICA",
    nivel: 99,
    creditos: 1,
    requisitos: [
      {
        materia: 2536321,
        nombreMateria: "FISICA TERMICA",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9002,
        nombreBancoElectivas:
          "BANCO ALTERNATIVO LABORATORI INTEGRADO DE FÍSICA",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2536501,
    nombreMateria: "LAB INTEGRADO DE FISICA",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9002,
    nombreBancoElectivas: "BANCO ALTERNATIVO LABORATORI INTEGRADO DE FÍSICA",
    nivel: 99,
    creditos: 1,
    requisitos: [
      {
        materia: 2536302,
        nombreMateria: "FÍSICA DE ONDAS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9002,
        nombreBancoElectivas:
          "BANCO ALTERNATIVO LABORATORI INTEGRADO DE FÍSICA",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2536503,
    nombreMateria: "LAB INTEGRADO DE FISICA",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9002,
    nombreBancoElectivas: "BANCO ALTERNATIVO LABORATORI INTEGRADO DE FÍSICA",
    nivel: 99,
    creditos: 1,
    requisitos: [
      {
        materia: 2536311,
        nombreMateria: "FÍSICA DE CAMPOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9002,
        nombreBancoElectivas:
          "BANCO ALTERNATIVO LABORATORI INTEGRADO DE FÍSICA",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508913,
    nombreMateria: "INGENIERÍA WEB",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9003,
    nombreBancoElectivas: "LINEA ENFASÍS INGENIÉRIA DE SOFTWARE Y SISTE DE IN",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2508609,
        nombreMateria: "BASES DE DATOS Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 32,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508914,
    nombreMateria: "BIG DATA",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9003,
    nombreBancoElectivas: "LINEA ENFASÍS INGENIÉRIA DE SOFTWARE Y SISTE DE IN",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2508609,
        nombreMateria: "BASES DE DATOS Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 32,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508915,
    nombreMateria: "PRUEBAS DE SOFTWARE",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9003,
    nombreBancoElectivas: "LINEA ENFASÍS INGENIÉRIA DE SOFTWARE Y SISTE DE IN",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2508703,
        nombreMateria: "CALIDAD DE SOFTWARE",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 39,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508916,
    nombreMateria: "DESARROLLO DE APLICACIONES EMPRESARIALES",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9003,
    nombreBancoElectivas: "LINEA ENFASÍS INGENIÉRIA DE SOFTWARE Y SISTE DE IN",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2508608,
        nombreMateria: "ARQUITECTURA DE SOFTWARE",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 31,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 2508609,
        nombreMateria: "BASES DE DATOS Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 32,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508917,
    nombreMateria: "GESTIÓN DE TIC",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9003,
    nombreBancoElectivas: "LINEA ENFASÍS INGENIÉRIA DE SOFTWARE Y SISTE DE IN",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2508702,
        nombreMateria: "FUNDAMENTOS DE SISTEMAS DE INFORMACIÓN",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 38,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508918,
    nombreMateria: "SEGURIDAD DE LA INFORMACIÓN",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9003,
    nombreBancoElectivas: "LINEA ENFASÍS INGENIÉRIA DE SOFTWARE Y SISTE DE IN",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2508610,
        nombreMateria: "COMUNICACIONES Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 34,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508401,
    nombreMateria:
      "INTRODUCCION A LA INTELINGENCIA ARTIFICIAL PARA LAS CCIAS E INGENIERIAS",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9004,
    nombreBancoElectivas: "LINEA ENFASÍS CIENCIAS DE LA COMPUTACIÓN",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 65,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9004,
        nombreBancoElectivas: "LINEA ENFASÍS CIENCIAS DE LA COMPUT",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508921,
    nombreMateria: "BLOCKCHAIN",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9004,
    nombreBancoElectivas: "LINEA ENFASÍS CIENCIAS DE LA COMPUTACIÓN",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2555231,
        nombreMateria: "CÁLCULO INTEGRAL",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 12,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 2508608,
        nombreMateria: "ARQUITECTURA DE SOFTWARE",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 31,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508943,
    nombreMateria: "OPTIMIZACIÓN",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9004,
    nombreBancoElectivas: "LINEA ENFASÍS CIENCIAS DE LA COMPUTACIÓN",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2508308,
        nombreMateria: "TEORÍA DE LA PROBABILIDAD Y COLAS",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 18,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508944,
    nombreMateria: "MATEMÁTCIAS DISCRETAS III",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9004,
    nombreBancoElectivas: "LINEA ENFASÍS CIENCIAS DE LA COMPUTACIÓN",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2508303,
        nombreMateria: "MATEMÁTICAS DISCRETAS II",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 15,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508945,
    nombreMateria: "MATEMÁTICAS DISCRETAS IV",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9004,
    nombreBancoElectivas: "LINEA ENFASÍS CIENCIAS DE LA COMPUTACIÓN",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2508303,
        nombreMateria: "MATEMÁTICAS DISCRETAS II",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 15,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508946,
    nombreMateria: "FUNDAMENTOS DE DEEP LEARNING",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9004,
    nombreBancoElectivas: "LINEA ENFASÍS CIENCIAS DE LA COMPUTACIÓN",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2508611,
        nombreMateria: "MODELOS Y SIMULACIÓN DE SISTEMAS II",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 33,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508947,
    nombreMateria: "FUNDAMENTOS EN PROCESAMIENTO DE LENGUAJE NATURAL",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9004,
    nombreBancoElectivas: "LINEA ENFASÍS CIENCIAS DE LA COMPUTACIÓN",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2508611,
        nombreMateria: "MODELOS Y SIMULACIÓN DE SISTEMAS II",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 33,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508973,
    nombreMateria: "DISEÑO DE CIRCUITOS DIGITALES",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9005,
    nombreBancoElectivas: "LINEA ENFASÍS ING COMPUTADORES Y COMUNICACIÓ DE DA",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2508303,
        nombreMateria: "MATEMÁTICAS DISCRETAS II",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 15,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508974,
    nombreMateria: "SISTEMAS PARALELOS",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9005,
    nombreBancoElectivas: "LINEA ENFASÍS ING COMPUTADORES Y COMUNICACIÓ DE DA",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2508716,
        nombreMateria: "ARQUITECTURA DE COMPUTADORES Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 40,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508975,
    nombreMateria: "SISTEMAS EMBEBIDOS",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9005,
    nombreBancoElectivas: "LINEA ENFASÍS ING COMPUTADORES Y COMUNICACIÓ DE DA",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2508716,
        nombreMateria: "ARQUITECTURA DE COMPUTADORES Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 40,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508976,
    nombreMateria: "SEMINARIO VOZ IP",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9005,
    nombreBancoElectivas: "LINEA ENFASÍS ING COMPUTADORES Y COMUNICACIÓ DE DA",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2508610,
        nombreMateria: "COMUNICACIONES Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 34,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508977,
    nombreMateria: "PROCESAMIENTO DIGITAL DE IMÁGENES",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9005,
    nombreBancoElectivas: "LINEA ENFASÍS ING COMPUTADORES Y COMUNICACIÓ DE DA",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2508716,
        nombreMateria: "ARQUITECTURA DE COMPUTADORES Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 40,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508978,
    nombreMateria: "COMPUTACIÓN MÓVIL",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9005,
    nombreBancoElectivas: "LINEA ENFASÍS ING COMPUTADORES Y COMUNICACIÓ DE DA",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2508716,
        nombreMateria: "ARQUITECTURA DE COMPUTADORES Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 40,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508979,
    nombreMateria: "INTERNET DE LAS COSAS",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9005,
    nombreBancoElectivas: "LINEA ENFASÍS ING COMPUTADORES Y COMUNICACIÓ DE DA",
    nivel: 99,
    creditos: 4,
    requisitos: [
      {
        materia: 2508610,
        nombreMateria: "COMUNICACIONES Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 34,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 2508716,
        nombreMateria: "ARQUITECTURA DE COMPUTADORES Y LABORATORIO",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 40,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508020,
    nombreMateria: "ELECTIVA SOCIO HUMANÍSTICA I",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508021,
    nombreMateria: "ELECTIVA SOCIO HUMANÍSTICA II",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508022,
    nombreMateria: "ELECTIVA SOCIO HUMANÍSTICA III",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508023,
    nombreMateria: "INTRODUCCIÓN A LAS CIENCIAS",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508024,
    nombreMateria: "HISTORIA CONTEMPORÁNEA",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 48,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9006,
        nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508025,
    nombreMateria: "HISTORIA DE LA INGENIERÍA",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 48,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9006,
        nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508026,
    nombreMateria: "ARGUMENTACIÓN Y LECTOESCRITURA",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 16,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9006,
        nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508027,
    nombreMateria: "INTRODUCCIÓN A LA PSICOLOGÍA",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 48,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9006,
        nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508028,
    nombreMateria: "RAZONAMIENTO Y CONOCIMIENTO",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 48,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9006,
        nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508029,
    nombreMateria: "LEGISLACIÓN",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 48,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9006,
        nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508030,
    nombreMateria: "PENSAMIENTO CRÍTICO Y NUEVAS TECNOLOGÍAS",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 16,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9006,
        nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508031,
    nombreMateria: "PENSAR LA HISTORIA",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 16,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9006,
        nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508032,
    nombreMateria: "HUMANIDAD Y ECONOMÍA",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 16,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9006,
        nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508033,
    nombreMateria: "CIENCIA TÉCNICA Y SOCIEDAD",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 16,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9006,
        nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508034,
    nombreMateria: "ESTRATEGIAS PSICOSOCIALES PARA EL INGENIERO DE SISTEMAS",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 48,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9006,
        nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508035,
    nombreMateria: "FILOSOFÍA DE LA INTELIGENCIA ARTIFICIAL",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2539101,
        nombreMateria: "LECTOESCRITURA",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 13,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2517203,
    nombreMateria: "LENGUA DE SEÑAS NIVEL 1",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 60,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9006,
        nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2517204,
    nombreMateria: "HABILIDADES GERENCIALES",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 60,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9006,
        nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2517206,
    nombreMateria: "HABILIDADES COMUNICATIVAS (LECTO ESCRITURA II)",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 2539101,
        nombreMateria: "LECTOESCRITURA",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 13,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2517208,
    nombreMateria: "GESTIÓN HUMANA PARA INGENIEROS",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 60,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9006,
        nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2566330,
    nombreMateria: "CREATIVIDAD PARA EMPRENDER",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 60,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9006,
        nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2566341,
    nombreMateria: "EMPRENDIMIENTO",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 60,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9006,
        nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2566342,
    nombreMateria: "PLAN DE NEGOCIOS",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9006,
    nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
    nivel: 99,
    creditos: 3,
    requisitos: [
      {
        materia: 60,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9006,
        nombreBancoElectivas: "SOCIOHUMANÍSTICOS",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508001,
    nombreMateria: "SEMESTRE DE INDUSTRIA",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9007,
    nombreBancoElectivas: "PRÁCTICA ACADÉMICA",
    nivel: 99,
    creditos: 12,
    requisitos: [
      {
        materia: 2508701,
        nombreMateria: "FUNDAMENTOS DE INVESTIGACIÓN",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 37,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 132,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9007,
        nombreBancoElectivas: "PRÁCTICA ACADÉMICA",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508002,
    nombreMateria: "TRABAJO DE GRADO",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9007,
    nombreBancoElectivas: "PRÁCTICA ACADÉMICA",
    nivel: 99,
    creditos: 12,
    requisitos: [
      {
        materia: 2508701,
        nombreMateria: "FUNDAMENTOS DE INVESTIGACIÓN",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 37,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 132,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9007,
        nombreBancoElectivas: "PRÁCTICA ACADÉMICA",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508003,
    nombreMateria: "EMPRESARISMO",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9007,
    nombreBancoElectivas: "PRÁCTICA ACADÉMICA",
    nivel: 99,
    creditos: 12,
    requisitos: [
      {
        materia: 2508701,
        nombreMateria: "FUNDAMENTOS DE INVESTIGACIÓN",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 37,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 132,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9007,
        nombreBancoElectivas: "PRÁCTICA ACADÉMICA",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508004,
    nombreMateria: "PROYECTOS DE INVESTIGACIÓN",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9007,
    nombreBancoElectivas: "PRÁCTICA ACADÉMICA",
    nivel: 99,
    creditos: 12,
    requisitos: [
      {
        materia: 2508701,
        nombreMateria: "FUNDAMENTOS DE INVESTIGACIÓN",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 37,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 132,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9007,
        nombreBancoElectivas: "PRÁCTICA ACADÉMICA",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
  {
    programa: 504,
    nombrePrograma: "INGENIERÍA DE SISTEMAS",
    version: 4,
    indicadorVersionActual: "N",
    materia: 2508005,
    nombreMateria: "PRÁCTICA SOCIAL",
    tipoMateria: "ELECTIVA",
    consecutivoMateria: 9007,
    nombreBancoElectivas: "PRÁCTICA ACADÉMICA",
    nivel: 99,
    creditos: 12,
    requisitos: [
      {
        materia: 2508701,
        nombreMateria: "FUNDAMENTOS DE INVESTIGACIÓN",
        tipoMateria: "OBLIGATORIA",
        consecutivoMateria: 37,
        nombreBancoElectivas: "  ",
        tipoRequisito: "PRERREQ",
      },
      {
        materia: 132,
        nombreMateria: "CREDITOS",
        tipoMateria: "ELECTIVA",
        consecutivoMateria: 9007,
        nombreBancoElectivas: "PRÁCTICA ACADÉMICA",
        tipoRequisito: "PRERREQCRED",
      },
    ],
  },
];
